### PR TITLE
Use ansible fact instead of yum variable for yum repos.

### PR DESCRIPTION
**Pull request by soulesn**
Replaced releasever with {{ ansible_distribution_version | int }} in the yum rpm repos.   In RHEL 6.x was providing the minor release (.x), which made the URLs invalid.

### CODE REVIEW

**Comment by jaredledvina** [comment]
Thanks for the PR! Lemme see if I can TravisCI unstuck to get the builds through. 

Interesting that REHL 6 differs like this from CentOS 6 but, also not too surprising. Now that you've mentioned it, if REHL has some free Docker containers for testing integrations, it wouldn't be too hard for me to include that in the Travis build as well.

**Comment by jaredledvina** [comment]
@soulesn While I work on getting this in, for the time being you can set the following variable for your hosts if you haven't to work around this issue:
```yaml
sensu_go_repos_overrides:
yum:
  rpm: https://packagecloud.io/sensu/stable/el/{{ ansible_distribution_version | int }}/$basearch
  rpm-src: https://packagecloud.io/sensu/stable/el/{{ ansible_distribution_version | int }}/SRPMS
```

That should do the trick.

**Comment by soulesn** [comment]
Thanks for getting back to me.  I haven’t tested my change using the pipenv/docker/molecule environment, but I did test it using ansible to deploy sensu to a SL 6.3 VM, and that seemed to work fine.

**Comment by soulesn** [comment]
Ok, thanks!

**Comment by jaredledvina** [comment]
Welp, looks like CentOS doesn't like this.
Build failure: https://travis-ci.com/jaredledvina/sensu-go-ansible/jobs/204619037#L765

Seems like the generate URL ends up being:
```
https://packagecloud.io/sensu/stable/el/0/x86_64/repodata/repomd.xm
```

**Comment by soulesn** [comment]
Works for SL.  Sorry, I said RHEL earlier, but really meant SL.  They're just about interchangeable, so I wouldn't expect there to be a difference, but then again, I didn't think CentOS would be so different either...

**Comment by jaredledvina** [comment]
Works for me! Thanks!

**Pull request merged**
